# Generated by Django 5.2.10 on 2026-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
