# Generated by Django 5.2.10 on 2026-02-25 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0003_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tools_enabled",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Boolean flags for enabled tools (semgrep/osv/gitleaks).",
                    ),
                ),
                (
                    "severity_threshold",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("semgrep_timeout_seconds", models.PositiveIntegerField(default=600)),
                ("osv_timeout_seconds", models.PositiveIntegerField(default=600)),
                ("gitleaks_timeout_seconds", models.PositiveIntegerField(default=600)),
                ("retention_days", models.PositiveIntegerField(default=1)),
                (
                    "gitleaks_rule_severity_overrides",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-timestamp", "-created_at"]},
        ),
        migrations.AddField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="entity_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("scan_queued", "Scan Queued"),
                    ("scan_started", "Scan Started"),
                    ("scan_completed", "Scan Completed"),
                    ("scan_failed", "Scan Failed"),
                    ("export_json_downloaded", "Export JSON Downloaded"),
                    ("export_markdown_downloaded", "Export Markdown Downloaded"),
                    ("policy_updated", "Policy Updated"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="scans_audit_action_ff0141_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="scans_audit_entity__f523c1_idx",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_policy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
