# Generated by Django 5.2.10 on 2026-02-25 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0004_policy_alter_auditlog_options_auditlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="scan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="scans.scan",
            ),
        ),
    ]
