# Generated by Django 5.2.10 on 2026-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="repo_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
