# Generated by Django 5.2.10 on 2026-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0001_initial"),
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("scan", "fingerprint"), name="unique_scan_fingerprint"
            ),
        ),
    ]
