# Generated by Django 5.2.10 on 2026-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0002_finding_unique_scan_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="ai_explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_fix_suggestion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_patch_diff",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
