# Generated by Django 5.2.10 on 2026-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0003_finding_ai_explanation_finding_ai_fix_suggestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="finding",
            name="references",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="finding",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
